### ISSUE TITLE
SRV records ignored?

### ISSUE THREAD

**Issue by daudo** [matrix-org/matrix-federation-tester#101]
I've setup a homeserver running on matrix.example.com and want to federate it using our base domain example.com.

I've read https://github.com/matrix-org/synapse/blob/master/docs/federate.md and https://matrix.org/docs/spec/server_server/latest#resolving-server-names and hopefully configured everything correctly.

matrix-federation-tester however tells me that there's an MatchingServerName error.

If I can, I'd like to avoid the well-known approach and have instead configured SRV records:

```
$ dig -t SRV _matrix._tcp.example.com @8.8.8.8
; <<>> DiG 9.16.1 <<>> -t SRV _matrix._tcp.example.com @8.8.8.8
;; global options: +cmd
;; Got answer:
[...]
;; QUESTION SECTION:
;_matrix._tcp.example.com.	IN	SRV

;; ANSWER SECTION:
_matrix._tcp.example.com. 3599 IN	SRV	10 0 443 matrix.example.com.
[...]
```
The homeserver itself is working like a charm, only federation refuses to behave nicely.

Any ideas what else could be wrong?

**Comment by richvdh** [comment]
this isn't the place for support in setting up a homeserver.

**Comment by daudo** [comment]
ok, I understand. The very last I actually need or want is someone supporting me how to set up a homeserver, I can perfectly handle that myself.

What I'd like to understand however, is why this very project "matrix-federation-tester" reports a MatchingServerName error when everything is setup as required in:

https://github.com/matrix-org/synapse/blob/master/docs/federate.md
and particularly in
https://matrix.org/docs/spec/server_server/latest#resolving-server-names

And if you don't think there can be an error in matrix-federation-tester, fine.

**Comment by richvdh** [comment]
I think if there was a bug in matrix-federation-tester, we'd have noticed by now. The problem is almost certainly in your server setup, or in your use of the federation tester. If you think otherwise, please supply a demonstration (which probably involves telling us your domain name).

**Comment by martinetd** [comment]
Actually might be something to improve in the federation tester error display; I just migrated server and .well-known wasn't set up correctly and the main page didn't give any error except "No SRV records".

The json output gave proper details though so it's just a display issue; I'd guess he never went as far as looking at the json though... :p
