### ISSUE TITLE
Non-successful looking page for a successful federation request

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-federation-tester#102]
![image](https://user-images.githubusercontent.com/2072976/78770029-fcf8da80-7985-11ea-98f5-137e3fdec8b9.png)

meanwhile https://federationtester.matrix.org/api/report?server_name=osgeo.org believes that `FederationOK` is `true`

**Comment by richvdh** [comment]
https://federationtester.matrix.org/#osgeo.org says "Got 1 connection report" for me. Perhaps there was a transient error?

**Comment by richvdh** [comment]
worksforme
