### ISSUE TITLE
Could this tool check if TURN configuration is working ?

### ISSUE THREAD

**Issue by n-peugnet** [matrix-org/matrix-federation-tester#111]
**Is your feature request related to a problem? Please describe.**
I didn't exactly understand how TURN is supposed to interact with synapse, but I have found it difficult to configure it correctly and also to test if everything is working. Currently to test my TURN setup I have to call multiple users on different home-servers and over different networks. I guess there is a better way to test this and I thought that maybe it could be done in this project.

**Describe the solution you'd like**
As I didn't exactly understand how TURN works I cannot say exactly what would be the ideal solution, but I guess some more fields in the json with the result of the test would be perfect. I know [this tool](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) is able to check in some ways if a TURN server works.

**Comment by richvdh** [comment]
the problem with testing TURN is that you need to authenticate as a matrix client - so (aside from the fact that it doesn't really fit into the remit of a *federation* tester), you'd have to hand over login detains for your matrix server to the test tool.

Basically I think this is a bit out of scope for the federation tester currently; you might look at tools like https://test.voip.librepush.net/ instead, though I can't vouch for its reliability currently.
