### ISSUE TITLE
federation-tester is querying regularly on ip:8448 instead honoring hostname/domain and well-known

### ISSUE THREAD

**Issue by ne20002** [matrix-org/matrix-federation-tester#134]
I run my synapse server on port 443 and for this I have a well-known file pointing to the correct hostname and port 443.
This works well and even federation-tester is showing an ok (green).

But it seems the federation-tester or some other bot from its ip addresses 94.237.61.73 and 2a04:3541:1000:0500:6866:a4ff:fe4c:5e7b is regularly querying my host by ip on port 8448 and 443. This results in a ban as I consider such connection attempts to be illegal (ip is shared by multiple services so only connections with SNI are allowed).

How can I prevent federation-tester from doing such kind of bot search?

**Comment by richvdh** [comment]
This may not be the hosted federation tester; there are a number of other services which use the same public IP addresses.

I'm afraid I don't know what "querying my host by ip on port 8448 and 443" actually means. You mean you're seeing TLS connection attempts without SNI?

I don't think we can do much without knowing more details about your server name/IP address and when you are seeing connection attempts. Suggest emailing `support@matrix.org`.
