### ISSUE TITLE
Does certificate error prevent other servers from getting room information?

### ISSUE THREAD

**Issue by JeanPaulLucien** [matrix-org/matrix-federation-tester#138]
I checked server `matrix.heiming.info` using https://federationtester.matrix.org and I got the text below:
```
There was an error looking up homeserver version information: Get "matrix://matrix.heiming.info/_matrix/federation/v1/version": x509: certificate has expired or is not yet valid: current time 2023-06-19T13:59:49Z is after 2023-04-25T19:38:21Z
WARN: Could not find a valid certificate for 77.10.65.228:8448. See [this documentation](https://github.com/matrix-org/synapse/blob/master/docs/MSC1711_certificates_FAQ.md#configuring-certificates-for-compatibility-with-synapse-100) for instructions on how to fix this.
ERROR: on 77.10.65.228:8448: x509: certificate has expired or is not yet valid: current time 2023-06-19T13:59:49Z is after 2023-04-25T19:38:21Z
```
I have registered successful on this server, but it does not display rooms from other Matrix servers. Is that because certificate has expired?

As I know this error allows you to register, sign in. I would to add information for what issues erros with cert is reason.

**Comment by t3chguy** [comment]
@JeanPaulLucien clients can ignore TLS issues (you can manually ignore them in a web browser for example) but servers will not ignore them. So yes the expired cert is likely to blame for your broken federation, though it may not be the only thing.
