### ISSUE TITLE
Plain text endpoint does not work on matrix.org instance

### ISSUE THREAD

**Issue by djmaze** [matrix-org/matrix-federation-tester#139]
When calling `https://matrix.org/federationtester/api/federation-ok?server_name=<server_name>`, the server just returns a 404.

**Comment by richvdh** [comment]
At least part of the problem here is that the hosted version is still on v0.7

**Comment by richvdh** [comment]
Fixed. Please don't use https://matrix.org/federationtester (or https://federationtester.matrix.org) as part of your production infrastructure though; we make no promises as to its reliability and reserve the right to turn it off or restrict access to it without notice if it becomes a significant cost.

**Comment by richvdh** [comment]
(for links: this endpoint was added in #132)
