### ISSUE TITLE
Documentation on usage with prometheus

### ISSUE THREAD

**Issue by Z3hka** [matrix-org/matrix-federation-tester#140]
I was looking for a way to have prometheus do blackbox-monitoring on my matrix homeserver and came across this project that seems to do some things with prometheus but i can't find any instructions about if prometheus is only used in the inner workings of this tool if it is possible to get replies in prometheus format.
I saw some lines about a /metrics endpoint in the sourcecode, but both https://federationtester.matrix.org/metrics and https://federationtester.matrix.org/api/metrics return 404 (but deliver different 404 Error pages)

I would be grateful if you could clarify that and possibly if there is a way to do this add this to the README.

Thanks in advance

**Comment by richvdh** [comment]
the metrics endpoint is for monitoring the health of the federation tester itself, so is only appropriate if you host your own instance.

Please don't use the hosted https://federationtester.matrix.org yourself for any automated testing.
