### ISSUE TITLE
Federation tester can't find .well-known file

### ISSUE THREAD

**Issue by westerguard** [matrix-org/matrix-federation-tester#144]
Since a little while, the federation tester errors out for my matrix homeserver ([wcore.org](https://federationtester.matrix.org/#wcore.org)).

When I take a look at [the json report](https://federationtester.matrix.org/api/report?server_name=wcore.org), it shows `"No .well-known found"`. 

That seems strange, because if I look it up myself at [https://wcore.org/.well-known/matrix/server](https://wcore.org/.well-known/matrix/server), the output is what you would expect:
`{
    "m.server": "matrix.wcore.org:8448"
}`

Any clue why the federation tester says 'No .well-known found', while the .well-known seems to be in the right place?

**Comment by tulir** [comment]
The server is broken, it blocks any user agent containing the substring `Go-http-client/`

```
$ curl https://wcore.org/.well-known/matrix/server -H "User-Agent: Go-http-client/1.1"
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

**Comment by westerguard** [comment]
Thank you for pointing me in the right direction! 

I started a ticket with my hosting provider how we can resolve this.
