### ISSUE TITLE
fed tester seems to be testing the cert in ip:port instead of hostname:port if .well-known is used

### ISSUE THREAD

**Issue by Bubu** [matrix-org/matrix-federation-tester#23]
Example here: https://matrix.org/federationtester/api/report?server_name=bubu1.eu

It should be getting the cert from `matrix.bubu1.eu:443`, instead it connects to `176.9.145.28:443` which has a different cert.

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/matrix-federation-tester/issues/21
