### ISSUE TITLE
Fedtester sometimes takes forever to complete a test

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-federation-tester#29]
Testing a server such as `amorgan.xyz` returns immediately, whereas testing `sw1v.org` takes a very long time.

We seem to be waiting on some request and then timing out after some amount of time, causing the tests to still display correctly.

Need to figure out what request is timing out.

**Comment by richvdh** [comment]
https://matrix.org/federationtester/api/report?server_name=sw1v.org returns within a couple of seconds for me. Perhaps it's caching something.

(Some logging might be helpful so that we can see what it did for a given request)

**Comment by richvdh** [comment]
I'd assume this is a dup of #10
