### ISSUE TITLE
AllChecksOK does not mean that all checks are ok

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-federation-tester#30]
Apparently some checks aren't included in AllChecksOK, which is super misleading

**Comment by anoadragon453** [comment]
`ValidCertificate` wasn't included as it's not mandatory at the moment (it's technically fine if you have self-signed certs).

But maybe it should be because deadline is coming up for them?

**Comment by richvdh** [comment]
Oh, is that the only thing that's not included?

I think it should be, anyway.

**Comment by anoadragon453** [comment]
Can do.

**Comment by richvdh** [comment]
related: #11
