### ISSUE TITLE
Federation tester doesn't work with multi domain reversed proxy server

### ISSUE THREAD

**Issue by mrdemc** [matrix-org/matrix-federation-tester#31]
Because the federation tester is not actually connecting to the server using the domain/_matrix but instead resolving the IP for the domain and connecting to that IP, the tester is receiving the wrong certificate if the IP connection returns another certificate (the main certificate).

It should directly connect to the correct domain instead of trying to use the IP for the connection.

**Comment by richvdh** [comment]
I believe this is a dup of #28
