### ISSUE TITLE
Federation Tester complains about invalid certs when using SRV to an IP address

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-federation-tester#39]
If a server is using an SRV record that leads to an IP address and that IP address is not included in the target server's federation TLS certificate, then the certificate gets marked as valid even if `example.com` is included (it's a case of trying and failing to validate xx.xx.xx.xx:8448 vs. example.com:8448).

I'm of the mind that we should still fail, but use the new errors output to say that this is the case and that people should move to .well-known.

**Comment by richvdh** [comment]
> then the certificate gets marked as valid even if `example.com` is included

this sounds like correct behaviour?

> people should move to .well-known.

The idea is that a `.well-known` is normally unnecessary and you should just use the right cert

**Comment by anoadragon453** [comment]
LetsEncrypt doesn't seem to set up an IP address into the cert by default though.

**Comment by richvdh** [comment]
Indeed, certificates don't usually include an IP address, but that shouldn't matter as we should check for the original server name, not the target. 

> then the certificate gets marked as valid even if example.com is included

Did you mean *in*valid?

There is a separate problem with IP addresses: I don't think it is valid for a SRV to point to an IP address. You might want to check that though.

**Comment by richvdh** [comment]
@anoadragon453 I'm still very confused about what this issue is talking about.

**Comment by anoadragon453** [comment]
This issue spawned as a configuration error as part of @benparsons' server, which afaik used the community Ansible playbook (which may need to be adjusted to not set the SRV record to an IP address).

As [SRV cannot be an IP address](https://stackoverflow.com/a/41003845), this makes this whole issue moot.

**Comment by spantaleev** [comment]
The [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) playbook doesn't set SRV records on people's behalf.

In its [Configuring DNS](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/25bdc106174e23bf95c99d906b825fa64fcadee9/docs/configuring-dns.md), we do advise people to set a SRV record (before Synapse v1.0, at least), but it references a `matrix.<domain>` host, never an IP address.

So.. it's interesting exactly what happened and how.

**Comment by compgeniuses** [comment]
so, no solution was found for this issue.
