### ISSUE TITLE
ConnectionErrors "invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by Bubu** [matrix-org/matrix-federation-tester#40]
I get this error message when testing my server: https://matrix.org/federationtester/api/report?server_name=bubu1.eu

![image](https://user-images.githubusercontent.com/105185/52650430-89c31800-2eea-11e9-96a3-199024001f71.png)

**Comment by richvdh** [comment]
dup #41. In this case it looks like the reverse-proxy is expecting the Host header to be `matrix.bubu1.eu`, whereas it will be `bubu1.eu`, so returns a 404.

**Comment by vaab** [comment]
@richvdh Well, I'm also expecting (maybe wrongly, I can hear that) that if DNS SRV specifies ``matrix.bubu1.eu`` being the matrix server for ``bubu1.eu``, to go and talk to ``matrix.bubu1.eu`` by setting ``Host header`` to the same exact value (which is ``matrix.bubu1.eu``). Your comment is implying that it doesn't.
Is there a rationale here why this isn't the case ? Any links ? is matrix protocol actually asking for this (and thus, this setup won't actually work) or is this just a ``matrix-federation-tester`` quirk ?

**Comment by richvdh** [comment]
https://matrix.org/docs/spec/server_server/r0.1.1.html#resolving-server-names spells all this out.

**Comment by vaab** [comment]
Thanks, just adding this link here for whoever is interested for the rationale of why DNS SRV isn't using the given hostname as the ``Host:``:
https://github.com/matrix-org/matrix-doc/blob/master/proposals/1711-x509-for-federation.md#interaction-with-srv-records
