### ISSUE TITLE
give the federation tester a UI

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-federation-tester#6]
It would be nice if people could self-service on the federation tester, rather than having to be handheld. It was designed to have a UI added later; we should do so

**Comment by t3chguy** [comment]
there's a fancy UI for the tester now: https://neo.lain.haus/fed-tester/

**Comment by krombel** [comment]
And the related repo is here: https://github.com/f0x52/fed-tester

**Comment by richvdh** [comment]
F0x's UI is now hosted on the matrix infrastructure at https://matrix.org/federationtester/, so I'm calling this done.
