### ISSUE TITLE
federation tester doesn't work for russian homeservers

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-federation-tester#85]
https://isitblockedinrussia.com/?host=94.237.61.73

**Comment by MurzNN** [comment]
Can you just move (or proxy) service to subnet, near to `jitsi.riot.im` (94.237.57.21) or `scalar.vector.im` (104.31.71.95, 104.31.70.95), or proxy via Cloudflare? Those subnets are not blocked in Russia, and seems Russian government stop process of blocking new Telegram IP ranges (replaced them to DPI analyze).

**Comment by richvdh** [comment]
> Can you just move (or proxy) service to subnet, near to jitsi.riot.im (94.237.57.21) or scalar.vector.im (104.31.71.95, 104.31.70.95)

We don't control the whole subnet (though note that it's already close to jitsi.riot.im). Proxying outbound requests via other servers significantly complicates the operational complexity of our network. We made a particular effort when the main homeserver was blocked, but it's just not worth it for a test tool like the federation tester.

> or proxy via Cloudflare like matrix.org

*outbound* requests are not proxied via cloudflare. But sure, if you put inbound requests to your own homeserver behind cloudflare, that will fix it!

**Comment by richvdh** [comment]
https://isitblockedinrussia.com/?host=94.237.61.73 claims that the relevant IP address is no longer blocked - can anyone confirm?

**Comment by 532910** [comment]
Unfortunately, no. 94.237.61.73 is still blocked in russia. It's blocked by megafon (the uplink for my matrix homeserver) and by nevalink (my home ISP)

**Comment by 532910** [comment]
turn.matrix.org works fine, but I can't call my friend who is registered on matrix.org and uses it from ios app. His phone just not ringing but he receives the message that I'm ringing. (And he always can successfully call me.) Is there a way to debug it?

**Comment by richvdh** [comment]
I *believe* that most of the misguided IP blocks have been lifted.

**Comment by MurzNN** [comment]
Yes, Russian government stops blocking Telegram: https://en.wikipedia.org/wiki/Blocking_Telegram_in_Russia

>  It was officially unblocked on 19 June, 2020.
