### ISSUE TITLE
Cannot get enough information why these federation setup fails

### ISSUE THREAD

**Issue by CybotTM** [matrix-org/matrix-federation-tester#95]
Hi,

the tester is a nice tool, but somehow i'm missing crucial information from the tester why the following setup fails:

1. https://federationtester.matrix.org/api/report?server_name=netresearch.de
2. https://federationtester.matrix.org/api/report?server_name=matrix.netresearch.de

but the SRV records and server responses looking fine for me:

https://synapse.netresearch.de/_matrix/federation/v1/version
```json
{
    "server": {
        "name": "Synapse",
        "version": "1.3.1"
    }
}
```

https://synapse.netresearch.de/_matrix/key/v2/server/
```json
{
 "old_verify_keys":{},
 "server_name":"netresearch.de",
 "signatures":{
  "netresearch.de":{"ed25519:a_YdTI":"Wn8H4H3dDWdAARgidZqMcD6/WbH80jUoukpstWMEv+yxfNmEswj1c9sKjjWyycahWB3B254tfHGSignrbrTxDg"}
 },
 "tls_fingerprints":[],
 "valid_until_ts":1571211172828,
 "verify_keys":{
  "ed25519:a_YdTI":{"key":"IaRU9E6N0gpPTOnYYBSUJ+rTUUyBktIYScwFAsIApNI"}
 }
}
```

**Comment by richvdh** [comment]
your server's giving a 404:  

```
curl -H 'Host:netresearch.de' https://synapse.netresearch.de/_matrix/key/v2/server/
404 page not found
```

This isn't the right place to ask for support btw. Please try `#synapse:matrix.org`.
