### ISSUE TITLE
Confusing error message when SSL problem in SRV check

### ISSUE THREAD

**Issue by jaywink** [matrix-org/matrix-federation-tester#96]
Case;

* SRV record is set-up correctly (`domain.tld` delegates via SRV to `matrix.domain.tld`)
* There is no .well-known
* The homeserver `matrix.domain.tld` has a valid SSL certificate for `matrix.domain.tld` but not for `domain.tld` (as required by spec for SRV to work)

The error given by the federation tester is as follows (in the JSON output):

```
"ConnectionErrors": {
    "1.2.3.4:443": {
      "Message": "Non-200 response 404 from remote server"
    }
  },
```

**Comment by richvdh** [comment]
are you sure?

**Comment by Tahvok** [comment]
Same issue here.
My cert for subdomain is correct and working properly, however the parent domain is pointing to a completely unrelated website which I don't have control over.
The federation tester is complaining with same error:
https://federationtester.matrix.org/api/report?server_name=tahvok.com

**Comment by richvdh** [comment]
@Tahvok I see a completely different error for you: https://gist.github.com/richvdh/71913e1e8d382aaed1410978aeaeb97b.

I'm going to close this until someone can actually demonstrate the reported problem.

**Comment by tulir** [comment]
@jaywink's error seems perfectly normal if there's a web server/reverse proxy that has virtualhosts for both `domain.tld` and `matrix.domain.tld`. The web server will see it as a request to `domain.tld` (SNI is always set to what certs the client expects, `Host` header is generally the same as SNI). If there's no Matrix stuff on the `domain.tld` virtualhost, 404 is the correct response.
